### ISSUE TITLE
Quick start section add

### ISSUE THREAD

**Issue by simonebenati** [4xoc/netbox_sd#1]
Hello there,

Wanted to start using this for my staging environment.

How can I get started with this?
I've read a few time the docs and it's clear to me that this has to be on the same machine as prometheus but how do I run this?

Could you please add a very brief quick start commands just to get it sorted with the simplest promethues.yml snippet?

Thank you!

**Comment by 4xoc** [comment]
Did you happen to stumble upon the [wiki](https://github.com/4xoc/netbox_sd/wiki)? If so, what part do you struggle with?

**Comment by simonebenati** [comment]
Hello,

Sorry, no I didn't check the "wiki" section as I wasn't even aware of that section I was 100% tunnel-visioning on the README file.
I will check that one we can close the issue!

**Comment by 4xoc** [comment]
No worries :) Feel free to provide feedback in case the wiki is missing something.
